- hosts: all
  tasks:
    - name: Update system packages
      become: yes
      apt:
        update_cache: yes
        upgrade: no

- hosts: db
  roles:
    - database
  tags:
    - db

- hosts: app
  roles:
    - webapp
  tags:
    - app
