Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  N = 1
  (1..N).each do |machine_id|
    config.vm.define "condor-#{machine_id}" do |machine|
      machine.vm.hostname = "condor-#{machine_id}"
      machine.vm.network "private_network", ip: "10.0.0.#{20+machine_id}" , bridge: "en0: Wi-Fi (Wireless)"
    end
  end

end
