Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum install wget -y
    wget https://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
    rpm --import RPM-GPG-KEY-HTCondor
    cd /etc/yum.repos.d
    wget https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel8.repo
    yum install condor -y
    systemctl start condor
    systemctl enable condor
  SHELL

  N = 3
  (1..N).each do |machine_id|
    config.vm.define "condor-#{machine_id}" do |machine|
      machine.vm.hostname = "condor-#{machine_id}"
      machine.vm.network "private_network", ip: "10.0.0.#{20+machine_id}" , bridge: "en0: Wi-Fi (Wireless)"
    end
  end

end
