module Mapas where

import LI11718

mapas = [mapas128,mapas64,mapas16,mapas4]

{-|
Mapas predefinidos utilizados no torneio dos /bots/
na ronda de 128. Apenas mapas com alturas negativas,
sem rampas, sem curvas em U, sem peças adjacentes 
(sem possibilidade de atalhos) e sem cruzamentos.
-}
mapas128 :: [Mapa]
mapas128 = --constroi [Desce,CurvaDir,Avanca,Avanca,CurvaDir,Avanca,CurvaDir,Avanca,Avanca,CurvaDir,Avanca,CurvaDir,Avanca,Avanca,CurvaDir,Avanca,CurvaDir,Avanca,Avanca,CurvaDir]
           [Mapa ((2,1),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Norte) (-1),Peca Recta (-1),Peca (Curva Este) (-1),Peca Lava 0]
                             ,[Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Recta (-1),Peca Lava 0]
                             ,[Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Recta (-1),Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Oeste) (-1),Peca Recta (-1),Peca (Curva Sul) (-1),Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
           --constroi [Desce,Desce,CurvaDir,Avanca,CurvaDir,Avanca,Avanca,CurvaDir,Avanca,CurvaDir,Avanca,Avanca,CurvaDir,Avanca,CurvaDir,Avanca,Avanca,CurvaDir,Avanca,CurvaDir]
           ,Mapa ((2,1),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                              ,[Peca Lava 0,Peca (Curva Norte) (-2),Peca Recta (-2),Peca Recta (-2),Peca (Curva Este) (-2),Peca Lava 0]
                              ,[Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Recta (-2),Peca Lava 0]
                              ,[Peca Lava 0,Peca (Curva Oeste) (-2),Peca Recta (-2),Peca Recta (-2),Peca (Curva Sul) (-2),Peca Lava 0]
                              ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
           --constroi [Avanca,Avanca,CurvaDir,Avanca,CurvaEsq,CurvaDir,Avanca,Avanca,CurvaDir,Avanca,CurvaDir,Avanca,Avanca,CurvaEsq,Avanca,CurvaDir,Avanca,CurvaDir]
           ,Mapa ((2,1),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                              ,[Peca Lava 0,Peca (Curva Norte) (-1),Peca Recta (-1),Peca Recta (-1),Peca (Curva Este) (-1),Peca Lava 0,Peca Lava 0]
                              ,[Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0]
                              ,[Peca Lava 0,Peca (Curva Oeste) (-1),Peca Recta (-1),Peca (Curva Este) (-1),Peca (Curva Oeste) (-1),Peca (Curva Este) (-1),Peca Lava 0]
                              ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Recta (-1),Peca Lava 0]
                              ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Recta (-1),Peca Lava 0]
                              ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-1),Peca Recta (-1),Peca (Curva Sul) (-1),Peca Lava 0]
                              ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
             --constroi [Avanca,CurvaDir,CurvaEsq,CurvaDir,CurvaEsq,Avanca,CurvaEsq,CurvaDir,Avanca,Avanca,CurvaDir,Avanca,CurvaDir,Avanca,CurvaEsq,Avanca,CurvaDir,Avanca,Avanca,Avanca,CurvaDir,Avanca,Avanca,CurvaEsq,Avanca,CurvaDir,Avanca,CurvaDir]
           ,Mapa ((2,1),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                              ,[Peca Lava 0,Peca (Curva Norte) 1,Peca Recta 1,Peca (Curva Este) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                              ,[Peca Lava 0,Peca Recta 1,Peca Lava 0,Peca (Curva Oeste) 1,Peca (Curva Este) 1,Peca Lava 0,Peca (Curva Norte) 1,Peca Recta 1,Peca Recta 1,Peca (Curva Este) 1,Peca Lava 0]
                              ,[Peca Lava 0,Peca (Curva Oeste) 1,Peca Recta 1,Peca (Curva Este) 1,Peca (Curva Oeste) 1,Peca Recta 1,Peca (Curva Sul) 1,Peca Lava 0,Peca Lava 0,Peca Recta 1,Peca Lava 0]
                              ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Norte) 1,Peca Recta 1,Peca (Curva Sul) 1,Peca Lava 0]
                              ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 1,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                              ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 1,Peca Recta 1,Peca Recta 1,Peca Recta 1,Peca (Curva Sul) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                              ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
           -- quadrado, 2x CurvaEsq, 2x Sobe/Desce, rebaixado: constroi [Avanca, Avanca, Avanca, Avanca, Avanca, Avanca, CurvaEsq, Avanca, Avanca, Desce, Desce, Avanca, CurvaEsq, Avanca, Avanca, Avanca, Avanca, Avanca, Avanca, CurvaEsq, Avanca, Avanca, Sobe, Sobe, Avanca, CurvaEsq]
           , Mapa ((2,7),Este)[[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                              ,[Peca Lava 0,Peca (Curva Norte) (-4),Peca Recta (-4),Peca Recta (-4),Peca Recta (-4),Peca Recta (-4),Peca Recta (-4),Peca Recta (-4),Peca (Curva Este) (-4),Peca Lava 0]
                              ,[Peca Lava 0,Peca Recta (-4),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-4),Peca Lava 0]
                              ,[Peca Lava 0,Peca Recta (-4),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Sul) (-4),Peca Lava 0]
                              ,[Peca Lava 0,Peca (Rampa Sul) (-4),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Sul) (-3),Peca Lava 0]
                              ,[Peca Lava 0,Peca (Rampa Sul) (-3),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-2),Peca Lava 0]
                              ,[Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-2),Peca Lava 0]
                              ,[Peca Lava 0,Peca (Curva Oeste) (-2),Peca Recta (-2),Peca Recta (-2),Peca Recta (-2),Peca Recta (-2),Peca Recta (-2),Peca Recta (-2),Peca (Curva Sul) (-2),Peca Lava 0]
                              ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
           ]

{-|
Mapas predefinidos utilizados no torneio dos /bots/ na
ronda de 64. Igual ao 'mapas128' mas agora com alturas 
positivas, rampas pontuais e curvas em U.
-}
mapas64 :: [Mapa]
mapas64 = --constroi [Avanca,Avanca,CurvaDir,Avanca,CurvaDir,Avanca,Avanca,CurvaDir,Avanca,CurvaDir]
          [Mapa ((2,1),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Norte) 0,Peca Recta 0,Peca Recta 0,Peca (Curva Este) 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Recta 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
          --constroi [Avanca,Sobe,CurvaDir,Avanca,CurvaDir,Avanca,Avanca,CurvaDir,Desce,CurvaDir]
          ,Mapa ((2,1),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Norte) 0,Peca Recta 0,Peca (Rampa Este) 0,Peca (Curva Este) 1,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Rampa Sul) 0,Peca Lava 0,Peca Lava 0,Peca Recta 1,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Oeste) 1,Peca Recta 1,Peca Recta 1,Peca (Curva Sul) 1,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
          --constroi [Avanca,Sobe,Sobe,Avanca,CurvaDir,CurvaDir,CurvaEsq,CurvaDir,Avanca,Desce,Desce,Avanca,CurvaDir,Avanca,CurvaDir,Avanca]
          ,Mapa ((3,1),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Norte) 0,Peca Recta 0,Peca Recta 0,Peca (Rampa Este) 0,Peca (Rampa Este) 1,Peca Recta 2,Peca (Curva Este) 2,Peca Lava 0]
                             ,[Peca Lava 0,Peca Recta 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Norte) 2,Peca (Curva Sul) 2,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca (Rampa Este) 0,Peca (Rampa Este) 1,Peca Recta 2,Peca (Curva Sul) 2,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
          ,Mapa ((2,1),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Norte) 0,Peca (Rampa Este) 0,Peca (Curva Este) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Rampa Norte) (-1),Peca Lava 0,Peca (Curva Oeste) 1,Peca (Curva Este) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Oeste) (-1),Peca Recta (-1),Peca (Curva Este) (-1),Peca (Rampa Sul) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca (Rampa Sul) 2,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Sul) (-1),Peca (Curva Oeste) 3,Peca (Rampa Oeste) 2,Peca (Curva Este) 2,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Sul) 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Norte) 1,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 1,Peca (Rampa Este) 1,Peca (Rampa Oeste) 1,Peca (Curva Sul) 1,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
          ,Mapa ((3,9),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Norte) 1,Peca (Rampa Este) 1,Peca Recta 2,Peca Recta 2,Peca (Curva Este) 2,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 2,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 2,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 1,Peca Lava 0,Peca (Curva Norte) 2,Peca Recta 2,Peca (Curva Sul) 2,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Norte) 0,Peca Lava 0,Peca Recta 2,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Lava 0,Peca Recta 2,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Lava 0,Peca (Rampa Norte) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Lava 0,Peca Recta 1,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Norte) 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0,Peca Recta 1,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Recta 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 1,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Oeste) 0,Peca (Rampa Este) 0,Peca Recta 1,Peca Recta 1,Peca (Curva Sul) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]

          ]

{-|
Mapas predefinidos utilizados no torneio dos /bots/
na ronda de 16. Igual ao 'mapas64' mas agora com peças
adjacentes e cruzamentos pontuais.
-}
mapas16 :: [Mapa]
mapas16 = --constroi [Avanca,CurvaDir,Avanca,CurvaDir,Avanca,CurvaDir,Avanca,Avanca,Avanca,CurvaEsq,Avanca,CurvaEsq,Avanca,CurvaEsq,Avanca,Avanca]
          
          [Mapa ((4,3),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Norte) (-1),Peca Recta (-1),Peca (Curva Este) (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Oeste) (-1),Peca Recta (-1),Peca Recta (-1),Peca Recta (-1),Peca (Curva Este) (-1),Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Recta (-1),Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-1),Peca Recta (-1),Peca (Curva Sul) (-1),Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
          --constroi [Desce,Avanca,CurvaDir,Avanca,CurvaDir,Avanca,CurvaEsq,Avanca,Avanca,Desce,Desce,CurvaDir,CurvaDir,CurvaEsq,Avanca,CurvaDir,CurvaDir,CurvaEsq,Avanca,Sobe,Sobe,Sobe,CurvaDir,Avanca]
          ,Mapa ((4,1),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca (Curva Norte) 0,Peca Recta 0,Peca (Rampa Oeste) (-1),Peca Recta (-1),Peca (Curva Este) (-1),Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca (Rampa Norte) (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca (Rampa Norte) (-2),Peca Lava 0,Peca (Curva Norte) (-1),Peca Recta (-1),Peca (Curva Sul) (-1),Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca (Rampa Norte) (-3),Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Recta (-3),Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Norte) (-3),Peca (Curva Sul) (-3),Peca Lava 0,Peca (Rampa Norte) (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Oeste) (-3),Peca Recta (-3),Peca (Curva Este) (-3),Peca (Rampa Norte) (-3),Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-3),Peca (Curva Sul) (-3),Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
           --constroi [Sobe,CurvaDir,CurvaEsq,CurvaDir,CurvaEsq,Avanca,CurvaEsq,CurvaEsq,CurvaEsq,Avanca,CurvaEsq,CurvaDir,CurvaEsq,Avanca,CurvaEsq,CurvaEsq,CurvaEsq,Avanca,CurvaEsq,CurvaDir,CurvaEsq,Avanca,CurvaEsq,CurvaEsq,CurvaEsq,Avanca,CurvaDir,Desce,CurvaDir,CurvaEsq,CurvaDir,CurvaEsq,CurvaDir,CurvaEsq,CurvaDir,CurvaEsq,CurvaDir,CurvaEsq,CurvaDir,CurvaEsq,CurvaDir,CurvaDir]
          ,Mapa ((2,1),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Norte) 0,Peca (Rampa Este) 0,Peca (Curva Este) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Oeste) 0,Peca (Curva Este) 0,Peca (Curva Oeste) 1,Peca (Curva Este) 1,Peca (Curva Norte) 1,Peca (Curva Este) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca (Curva Este) 0,Peca (Curva Oeste) 1,Peca Recta 1,Peca (Curva Sul) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca (Curva Este) 0,Peca (Curva Oeste) 1,Peca (Curva Este) 1,Peca (Curva Norte) 1,Peca (Curva Este) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca (Curva Este) 0,Peca (Curva Oeste) 1,Peca Recta 1,Peca (Curva Sul) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca (Curva Este) 0,Peca (Curva Oeste) 1,Peca (Curva Este) 1,Peca (Curva Norte) 1,Peca (Curva Este) 1,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca (Curva Este) 0,Peca (Curva Oeste) 1,Peca Recta 1,Peca (Curva Sul) 1,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca (Rampa Este) 0,Peca (Curva Sul) 1,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
          -- constroi [Avanca,Avanca,Avanca,Avanca,CurvaEsq,Avanca,Avanca,Avanca,Avanca,CurvaEsq,Avanca,Desce,Avanca,Avanca,Avanca,Avanca,Avanca,Avanca,Avanca,Desce,Avanca,Avanca,CurvaDir,CurvaEsq,CurvaDir,CurvaEsq,CurvaDir,CurvaEsq,CurvaDir,Avanca,Avanca,Sobe,Avanca,CurvaDir,Avanca,Avanca,Avanca,Sobe,Desce,Avanca,Avanca,CurvaEsq,Avanca,Avanca,Avanca,CurvaEsq,Avanca,Avanca,Avanca,Avanca,CurvaEsq,Avanca,Sobe,Desce,Avanca,Avanca,Avanca,Avanca,CurvaEsq,Sobe,Desce,Avanca,Avanca,CurvaDir,Avanca,Avanca,Avanca,Avanca,Sobe,Avanca,CurvaDir,Avanca,Avanca,Avanca,Desce,Desce,Avanca,Avanca,CurvaEsq,Avanca,CurvaEsq,Avanca,Desce,Avanca,Sobe,Avanca,Avanca,Sobe,Avanca,Sobe,Avanca,Avanca]
          ,Mapa ((13,18),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Norte) (-1),Peca Recta (-1),Peca Recta (-1),Peca Recta (-1),Peca Recta (-1),Peca (Curva Este) (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Sul) (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Norte) (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Norte) (-1),Peca Recta (-1),Peca Recta (-1),Peca Recta (-1),Peca (Rampa Este) (-1),Peca (Rampa Oeste) (-1),Peca Recta (-1),Peca Recta (-1),Peca (Curva Sul) (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Rampa Norte) (-2),Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-1),Peca (Rampa Este) (-1),Peca (Rampa Oeste) (-1),Peca Recta (-1),Peca Recta (-1),Peca (Curva Este) (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Oeste) (-2),Peca (Curva Este) (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-2),Peca (Curva Este) (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-2),Peca (Curva Este) (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-2),Peca Recta (-2),Peca Recta (-2),Peca (Rampa Este) (-2),Peca Recta (-1),Peca Recta (-1),Peca Recta (-1),Peca Recta (-1),Peca Recta (-1),Peca Recta (-1),Peca Recta (-1),Peca (Rampa Este) (-1),Peca Recta 0,Peca (Curva Este) 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Sul) (-1),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Norte) (-2),Peca Recta (-2),Peca Recta (-2),Peca (Rampa Este) (-2),Peca (Rampa Este) (-1),Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca (Curva Oeste) (-2),Peca Recta (-2),Peca (Rampa Oeste) (-3),Peca Recta (-3),Peca (Rampa Este) (-3),Peca Recta (-2),Peca Recta (-2),Peca (Rampa Este) (-2),Peca Recta (-1),Peca (Rampa Este) (-1),Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0]
                             ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
          ]

{-|
Mapas predefinidos utilizados no torneio dos /bots/
na ronda de 4, a final. Vale tudo.
-}
mapas4 :: [Mapa]
mapas4 =
    [ -- muitos loops e curvas, altura lava: constroi [Avanca, Avanca, Avanca, CurvaEsq, CurvaEsq, CurvaEsq, Avanca, Avanca, CurvaDir, CurvaDir, CurvaDir, Avanca, Avanca, Avanca, CurvaEsq, CurvaEsq, CurvaEsq, Avanca, Avanca, CurvaDir, CurvaDir, CurvaDir, Avanca, Avanca, Avanca, CurvaEsq, CurvaEsq, CurvaEsq, Avanca, Avanca, CurvaDir, CurvaDir, CurvaDir, Avanca, Avanca, Avanca, CurvaEsq, CurvaEsq, CurvaEsq, Avanca, Avanca, CurvaDir, CurvaDir, CurvaDir, Avanca, Avanca, Avanca, CurvaEsq, CurvaEsq, CurvaEsq, Avanca, Avanca, CurvaDir, CurvaDir, CurvaDir, Avanca, Avanca, Avanca, CurvaEsq, CurvaEsq, CurvaEsq, Avanca, Avanca, CurvaDir, CurvaDir, CurvaDir, Avanca, CurvaDir, Avanca, CurvaDir, Avanca, Avanca, CurvaDir, CurvaEsq, Avanca, CurvaDir, CurvaEsq, Avanca, CurvaDir, CurvaEsq, Avanca, CurvaDir, CurvaEsq, Avanca, CurvaDir, CurvaEsq, Avanca, CurvaDir, Avanca, Avanca, CurvaDir]
      Mapa ((1,2),Norte) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Norte) 0,Peca (Curva Este) 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca (Curva Norte) 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca (Curva Norte) 0,Peca (Curva Este) 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Recta 0,Peca (Curva Norte) 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca (Curva Norte) 0,Peca (Curva Este) 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Recta 0,Peca (Curva Oeste) 0,Peca (Curva Sul) 0,Peca (Curva Norte) 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca (Curva Norte) 0,Peca (Curva Este) 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca (Curva Este) 0,Peca (Curva Oeste) 0,Peca (Curva Sul) 0,Peca (Curva Norte) 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca (Curva Norte) 0,Peca (Curva Este) 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca (Curva Este) 0,Peca (Curva Oeste) 0,Peca (Curva Sul) 0,Peca (Curva Norte) 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca (Curva Norte) 0,Peca (Curva Este) 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca (Curva Este) 0,Peca (Curva Oeste) 0,Peca (Curva Sul) 0,Peca (Curva Norte) 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca (Curva Este) 0,Peca (Curva Oeste) 0,Peca (Curva Sul) 0,Peca (Curva Norte) 0,Peca Recta 0,Peca (Curva Este) 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca (Curva Este) 0,Peca (Curva Oeste) 0,Peca (Curva Sul) 0,Peca Recta 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
      -- muitos loops outra vez, sobe/desce sem dar para atalhar fácilmente: constroi [Avanca, Avanca, Avanca, CurvaEsq, Sobe, CurvaEsq, CurvaEsq, Desce, Avanca, Avanca, CurvaDir, Desce, CurvaDir, CurvaDir, Sobe, Avanca, Avanca, Avanca, Avanca, CurvaEsq, Sobe, CurvaEsq, CurvaEsq, Desce, Avanca, Avanca, CurvaDir, Desce, CurvaDir, CurvaDir, Sobe, Avanca, Avanca, Avanca, Avanca, CurvaEsq, Sobe, CurvaEsq, CurvaEsq, Desce, Avanca, Avanca, CurvaDir, Desce, CurvaDir, CurvaDir, Sobe, Avanca, Avanca, Avanca, Avanca, CurvaEsq, Sobe, CurvaEsq, CurvaEsq, Desce, Avanca, Avanca, CurvaDir, Desce, CurvaDir, CurvaDir, Sobe, Avanca, Avanca, Avanca, Avanca, CurvaEsq, Sobe, CurvaEsq, CurvaEsq, Desce, Avanca, Avanca, CurvaDir, Desce, CurvaDir, CurvaDir, Sobe, Avanca, Avanca, Avanca, Avanca, CurvaEsq, Sobe, CurvaEsq, CurvaEsq, Desce, Avanca, Avanca, CurvaDir, Desce, CurvaDir, CurvaDir, Sobe, Avanca, CurvaDir, Avanca, CurvaDir, Avanca, Avanca, Avanca, CurvaDir, CurvaEsq, Avanca, Avanca, CurvaDir, CurvaEsq, Avanca, Avanca, CurvaDir, CurvaEsq, Avanca, Avanca, CurvaDir, CurvaEsq, Avanca, Avanca, CurvaDir, CurvaEsq, Avanca, Avanca, CurvaDir, Avanca, Avanca, CurvaDir]
    , Mapa ((2,3),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Norte) 1,Peca (Curva Este) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Norte) 0,Peca (Rampa Norte) 0,Peca Lava 0,Peca (Curva Norte) 1,Peca (Curva Este) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca (Curva Norte) 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0,Peca (Rampa Norte) 0,Peca (Rampa Norte) 0,Peca Lava 0,Peca (Curva Norte) 1,Peca (Curva Este) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Recta 0,Peca (Curva Norte) (-1),Peca (Rampa Este) (-1),Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0,Peca (Rampa Norte) 0,Peca (Rampa Norte) 0,Peca Lava 0,Peca (Curva Norte) 1,Peca (Curva Este) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Recta 0,Peca (Curva Oeste) (-1),Peca (Rampa Este) (-1),Peca (Curva Sul) 0,Peca (Curva Norte) (-1),Peca (Rampa Este) (-1),Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0,Peca (Rampa Norte) 0,Peca (Rampa Norte) 0,Peca Lava 0,Peca (Curva Norte) 1,Peca (Curva Este) 1,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca Recta 0,Peca (Curva Este) 0,Peca (Curva Oeste) (-1),Peca (Rampa Este) (-1),Peca (Curva Sul) 0,Peca (Curva Norte) (-1),Peca (Rampa Este) (-1),Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0,Peca (Rampa Norte) 0,Peca (Rampa Norte) 0,Peca Lava 0,Peca (Curva Norte) 1,Peca (Curva Este) 1,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca Recta 0,Peca (Curva Este) 0,Peca (Curva Oeste) (-1),Peca (Rampa Este) (-1),Peca (Curva Sul) 0,Peca (Curva Norte) (-1),Peca (Rampa Este) (-1),Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0,Peca (Rampa Norte) 0,Peca (Rampa Norte) 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca Recta 0,Peca (Curva Este) 0,Peca (Curva Oeste) (-1),Peca (Rampa Este) (-1),Peca (Curva Sul) 0,Peca (Curva Norte) (-1),Peca (Rampa Este) (-1),Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca Recta 0,Peca (Curva Este) 0,Peca (Curva Oeste) (-1),Peca (Rampa Este) (-1),Peca (Curva Sul) 0,Peca (Curva Norte) (-1),Peca (Rampa Este) (-1),Peca Recta 0,Peca (Curva Este) 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca Recta 0,Peca (Curva Este) 0,Peca (Curva Oeste) (-1),Peca (Rampa Este) (-1),Peca (Curva Sul) 0,Peca Recta 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0]
                        ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
    -- constroi [Avanca, CurvaDir, Avanca, CurvaDir, Avanca, Avanca, CurvaDir, Avanca, Desce, Desce, Avanca, Avanca, Avanca, CurvaDir, Desce, Desce, Avanca, Avanca, Avanca, Sobe, Avanca, CurvaDir, CurvaDir, Avanca, Avanca, CurvaEsq, Avanca, CurvaEsq, Avanca, Sobe, Avanca, Avanca, Sobe, Desce, Avanca, CurvaDir, Avanca, CurvaDir, CurvaEsq, Avanca, Desce, Desce, Avanca, Avanca, CurvaDir, Avanca, CurvaEsq, Avanca, Avanca, CurvaDir, Avanca, CurvaDir, Avanca, Sobe, Sobe, Avanca, CurvaEsq, CurvaEsq, Avanca, Avanca, Sobe, Avanca, CurvaDir, CurvaDir, Avanca, Sobe, Avanca, Avanca, Desce, Desce, Avanca, Avanca, CurvaEsq,CurvaDir, CurvaEsq, CurvaDir, CurvaEsq, Avanca, Avanca, Avanca, Avanca, Avanca, Avanca, Avanca, CurvaEsq, Avanca, Avanca, Avanca, Avanca, CurvaEsq, Avanca, Sobe, Avanca, Sobe, CurvaEsq, Avanca, Avanca, CurvaDir]
    , Mapa ((6,4),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Norte) (-2),Peca (Rampa Oeste) (-3),Peca (Rampa Oeste) (-4),Peca Recta (-4),Peca Recta (-4),Peca Recta (-4),Peca (Rampa Este) (-4),Peca Recta (-3),Peca (Curva Este) (-3),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Norte) (-3),Peca Recta (-3),Peca Recta (-3),Peca (Curva Sul) (-3),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-3),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca (Curva Norte) (-2),Peca Recta (-2),Peca Recta (-2),Peca Recta (-2),Peca Recta (-2),Peca Recta (-2),Peca Recta (-2),Peca Recta (-2),Peca (Curva Este) (-2),Peca (Curva Oeste) (-3),Peca Recta (-3),Peca (Rampa Este) (-3),Peca Recta (-2),Peca Recta (-2),Peca (Rampa Este) (-2),Peca (Rampa Oeste) (-2),Peca Recta (-2),Peca (Curva Este) (-2),Peca Lava 0]
                       ,[Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Sul) (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-2),Peca (Curva Este) (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-2),Peca Lava 0]
                       ,[Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Sul) (-1),Peca (Curva Norte) 0,Peca Recta 0,Peca (Curva Este) 0,Peca Lava 0,Peca (Curva Oeste) (-2),Peca (Curva Este) (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Norte) (-2),Peca (Curva Sul) (-2),Peca Lava 0]
                       ,[Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Recta 0,Peca Lava 0,Peca Recta 0,Peca Lava 0,Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca Lava 0,Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Norte) (-3),Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca (Curva Oeste) (-2),Peca Recta (-2),Peca (Rampa Este) (-2),Peca Recta (-1),Peca (Rampa Este) (-1),Peca (Curva Sul) 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Sul) (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Norte) (-4),Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Sul) (-1),Peca (Curva Norte) (-2),Peca (Curva Este) (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-4),Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Recta (-2),Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-4),Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta 0,Peca Recta (-2),Peca (Rampa Norte) (-3),Peca Lava 0,Peca (Curva Norte) (-4),Peca Recta (-4),Peca (Curva Sul) (-4),Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Norte) (-1),Peca (Rampa Sul) (-2),Peca (Rampa Norte) (-4),Peca Lava 0,Peca Recta (-4),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Recta (-1),Peca Recta (-4),Peca Lava 0,Peca Recta (-4),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-1),Peca (Curva Sul) (-1),Peca (Curva Oeste) (-4),Peca Recta (-4),Peca (Curva Sul) (-4),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]
    -- varios loops, rampas muito longas
    -- constroi [Avanca, Sobe, Avanca, Sobe, Avanca, Sobe, Avanca, Sobe, Avanca, Sobe, Avanca, Sobe, Avanca, Sobe, CurvaDir, CurvaDir, Desce, Desce, Desce, Desce, Desce, Desce, Desce, CurvaEsq, CurvaEsq, Avanca, Desce, Desce, Desce, Desce, CurvaDir, Avanca, CurvaDir, Avanca, CurvaDir, CurvaDir, CurvaDir, Avanca, CurvaDir, Avanca, Sobe, Avanca, CurvaEsq, CurvaEsq, CurvaEsq, Avanca, CurvaEsq, Avanca, Avanca, Sobe, Avanca, CurvaDir, CurvaDir, CurvaDir, Avanca, CurvaDir, Avanca, Avanca, CurvaDir, Avanca, Avanca, CurvaEsq, CurvaEsq, CurvaEsq, Avanca, CurvaEsq, Avanca, CurvaEsq, Avanca, Sobe, Avanca, Avanca, Avanca, CurvaEsq, CurvaEsq, CurvaEsq, Avanca, Avanca, Sobe, Avanca, CurvaDir, CurvaDir, CurvaDir, Avanca, Avanca, CurvaDir, Avanca, CurvaDir, Avanca, Avanca, Avanca, CurvaDir, Avanca, Sobe, Desce, CurvaEsq]
    , Mapa ((6,5),Este) [[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca (Curva Norte) 0,Peca Recta 0,Peca Recta 0,Peca Recta 0,Peca (Curva Este) 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Recta 0,Peca Lava 0,Peca (Curva Norte) 0,Peca (Curva Este) 0,Peca Recta 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca Recta 0,Peca (Curva Sul) 0,Peca (Rampa Sul) 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Rampa Norte) (-1),Peca Lava 0,Peca (Rampa Norte) 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-1),Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca (Rampa Este) 0,Peca Recta 1,Peca (Rampa Este) 1,Peca Recta 2,Peca (Rampa Este) 2,Peca Recta 3,Peca (Rampa Este) 3,Peca Recta 4,Peca (Rampa Este) 4,Peca Recta 5,Peca (Rampa Este) 5,Peca Recta 6,Peca (Rampa Este) 6,Peca (Curva Este) 7,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca (Curva Norte) (-1),Peca Recta (-1),Peca Recta (-1),Peca Recta (-1),Peca (Rampa Oeste) (-2),Peca Recta (-2),Peca (Curva Este) (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Norte) 0,Peca (Rampa Este) 0,Peca (Rampa Este) 1,Peca (Rampa Este) 2,Peca (Rampa Este) 3,Peca (Rampa Este) 4,Peca (Rampa Este) 5,Peca (Rampa Este) 6,Peca (Curva Sul) 7,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-1),Peca (Curva Sul) (-1),Peca Lava 0,Peca Lava 0,Peca (Curva Norte) (-2),Peca (Curva Este) (-2),Peca Recta (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) 0,Peca Recta 0,Peca (Rampa Oeste) (-1),Peca (Rampa Oeste) (-2),Peca (Rampa Oeste) (-3),Peca (Rampa Oeste) (-4),Peca (Curva Este) (-4),Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-2),Peca Recta (-2),Peca (Curva Sul) (-2),Peca (Curva Norte) (-2),Peca (Curva Este) (-2),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Norte) (-4),Peca (Curva Este) (-4),Peca Recta (-4),Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Recta (-2),Peca Lava 0,Peca (Curva Oeste) (-2),Peca Recta (-2),Peca (Rampa Oeste) (-3),Peca Recta (-3),Peca Recta (-3),Peca (Curva Este) (-3),Peca Lava 0,Peca (Curva Oeste) (-4),Peca Recta (-4),Peca (Curva Sul) (-4),Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-2),Peca Recta (-2),Peca Recta (-2),Peca (Curva Sul) (-2),Peca Lava 0,Peca Lava 0,Peca (Curva Norte) (-3),Peca Recta (-3),Peca (Rampa Oeste) (-4),Peca Recta (-4),Peca (Curva Sul) (-4),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca (Curva Oeste) (-3),Peca (Curva Sul) (-3),Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]
                       ,[Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0,Peca Lava 0]]

    ]

{-|
Propriedades do terreno predefinidas a ser utilizadas no torneio
dos /bots/.
-}
propriedades :: [Propriedades]
propriedades = [terra,gelo,asfalto]

terra, gelo, asfalto :: Propriedades
terra   = Propriedades 2 3 4 2 15 180
gelo    = Propriedades 0.3 0.4 2 1.5 15 270
asfalto = Propriedades 4 5 8 4 10 120





