Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.box_version = "3.0.38"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  N = 3
  (1..N).each do |id|
    config.vm.define "condor-#{id}" do |machine|
      machine.vm.hostname = "condor-#{id}"
      machine.vm.network "private_network", ip: "10.0.0.#{20 + id}" , bridge: "en0: Wi-Fi (Wireless)"

      machine.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook.yml"
      end
    end
  end

end
